<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice: {{ $billingReport->name }} — {{ $project->name }}</title>
    <style>
        body { font-family: Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1.4; color: #334155; margin: 0; padding: 24px; }
        .invoice-header { margin-bottom: 28px; padding-bottom: 16px; border-bottom: 2px solid #1e293b; }
        .invoice-title { font-size: 24px; font-weight: 800; color: #1e293b; margin: 0 0 4px 0; letter-spacing: 0.02em; }
        .invoice-subtitle { font-size: 12px; color: #64748b; margin: 0; }
        .meta { font-size: 11px; color: #64748b; margin-top: 12px; }
        .mno-note { font-size: 10px; color: #475569; margin-bottom: 24px; }
        h2 { font-size: 12px; font-weight: 700; color: #475569; margin: 20px 0 10px 0; text-transform: uppercase; letter-spacing: 0.05em; }
        table.invoice-table { width: 100%; max-width: 560px; border-collapse: collapse; margin: 8px 0; }
        table.invoice-table th, table.invoice-table td { border: 1px solid #e2e8f0; padding: 10px 14px; text-align: left; }
        table.invoice-table th { background: #f1f5f9; font-size: 10px; font-weight: 700; text-transform: uppercase; color: #475569; width: 65%; }
        table.invoice-table td { font-size: 11px; font-weight: 600; }
        table.invoice-table tr.total-row th { background: #e2e8f0; font-size: 11px; }
        table.invoice-table tr.total-row td { font-size: 13px; font-weight: 700; color: #1e293b; }
        .footer-note { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 9px; color: #94a3b8; }
        .print-banner { display: none; padding: 12px 24px; background: #fef3c7; border-bottom: 1px solid #f59e0b; font-size: 13px; color: #92400e; }
        @media screen { .print-banner { display: block; } }
        @media print { .print-banner { display: none !important; } }
    </style>
</head>
<body>
    @if(isset($showPrintBanner) && $showPrintBanner)
    <div class="print-banner" role="alert">
        <strong>Save as PDF:</strong> Use your browser’s Print (Mac: <kbd>Cmd+P</kbd>, Windows: <kbd>Ctrl+P</kbd>) and choose <strong>Save as PDF</strong> or <strong>Print to PDF</strong>.
    </div>
    @endif
    <div class="invoice-header">
        <h1 class="invoice-title">Invoice</h1>
        <p class="invoice-subtitle">{{ $project->name }} · Billing period: {{ $periodLabel }}</p>
        <p class="meta">Invoice reference: {{ $billingReport->name }} · Generated {{ now()->format('d M Y H:i') }}</p>
    </div>
    <p class="mno-note">This invoice is intended for the Mobile Network Operator (MNO). It summarises revenue, costs and share breakdown for the stated period.</p>

    <h2>Revenue &amp; costs</h2>
    <table class="invoice-table">
        <tr>
            <th>Gross revenue</th>
            <td>{{ $billingReport->gross_revenue?->amount_with_currency ?? '—' }}</td>
        </tr>
        @if($billingReport->cost_breakdown && count((array) $billingReport->cost_breakdown) > 0)
            @foreach($billingReport->cost_breakdown as $costName => $costAmount)
                @php
                    $amountStr = '—';
                    if (is_object($costAmount) && (property_exists($costAmount, 'amount_with_currency') || method_exists($costAmount, 'amount_with_currency'))) {
                        $amountStr = $costAmount->amount_with_currency ?? '—';
                    } elseif (is_array($costAmount) && isset($costAmount['amount_with_currency'])) {
                        $amountStr = $costAmount['amount_with_currency'];
                    }
                @endphp
                <tr>
                    <th>{{ $costName }}</th>
                    <td>{{ $amountStr }}</td>
                </tr>
            @endforeach
        @endif
        <tr class="total-row">
            <th>Total costs</th>
            <td>{{ $billingReport->costs?->amount_with_currency ?? '—' }}</td>
        </tr>
        <tr>
            <th>Sharable revenue (after costs)</th>
            <td>{{ $billingReport->sharable_revenue?->amount_with_currency ?? '—' }}</td>
        </tr>
    </table>

    <h2>Revenue share</h2>
    <table class="invoice-table">
        <tr>
            <th>Their share ({{ $project->their_share_percentage ?? 40 }}%)</th>
            <td>{{ $billingReport->their_share?->amount_with_currency ?? '—' }}</td>
        </tr>
        <tr>
            <th>Our share ({{ $project->our_share_percentage ?? 60 }}%)</th>
            <td>{{ $billingReport->our_share?->amount_with_currency ?? '—' }}</td>
        </tr>
        <tr class="total-row">
            <th>Total transactions (period)</th>
            <td>{{ number_format($billingReport->total_transactions ?? 0) }}</td>
        </tr>
    </table>

    <p class="footer-note">Invoice generated by TelcoFlo Studio. For the billing period {{ $periodLabel }}. This document may be sent to the MNO for reconciliation and settlement.</p>
</body>
</html>
