<?php

namespace App\Enums;

enum CacheName:string {
    case USERS = 'USERS';
    case SMS_ACCESS_TOKEN_RESPONSE = 'SMS_ACCESS_TOKEN_RESPONSE';
    case AIRTIME_BILLING_ACCESS_TOKEN_RESPONSE = 'AIRTIME_BILLING_ACCESS_TOKEN_RESPONSE';
}
